#!/usr/bin/env bash
# Runs the shipped comment-reference scanner over this repo's own source.
#
# The scanner (hooks/claude-code/comment-refs.sh) decides what a violation is
# and travels to other projects as part of the hook. This wrapper decides only
# what *this* repo counts as source, which is the part that cannot travel.
#
# Run: ./scripts/check-comment-refs.sh   (exit 1 on any finding)
set -euo pipefail

cd "$(dirname "$0")/.."

# Excluded, and why:
#   graphify-out/           generated knowledge graph
#   docs/ agents/ skills/ templates/   prose, not code comments — the standard
#                           exempts them and they cite issues on purpose
#   cli/internal/assets/    a gitignored mirror, regenerated by stage-assets.sh
#   **/testdata/**          fixtures are inputs to a test, not commentary; a
#                           legacy plugin reproduced there has to stay verbatim
#   *.md *.json *.png ...   no comment syntax, or prose
# A read loop rather than mapfile: macOS ships bash 3.2, which has no mapfile,
# and this has to run on a contributor's laptop as well as in CI.
files=()
while IFS= read -r f; do
  files+=("$f")
done < <(git ls-files \
  | grep -vE '^(graphify-out|docs|agents|skills|templates)/' \
  | grep -vE '(^|/)testdata/' \
  | grep -v '^cli/internal/assets/' \
  | grep -vE '\.(md|json|png|jpg|jpeg|svg|ico|lock|sum)$')

[ ${#files[@]} -gt 0 ] || { echo "no source files matched — refusing to report a pass"; exit 1; }

exec bash hooks/claude-code/comment-refs.sh "${files[@]}"
